import type { Token } from '../common/token.js';
import type { MarkdownIt } from '../index.js';
import type { ParserCore } from '../parse/parser_core.js';
export interface StreamStats {
    total: number;
    cacheHits: number;
    appendHits: number;
    unboundedAppendHits?: number;
    tailHits: number;
    fullParses: number;
    resets: number;
    chunkedParses?: number;
    lastMode: 'idle' | 'cache' | 'append' | 'tail' | 'full' | 'reset' | 'chunked';
}
export declare class StreamParser {
    private readonly core;
    private cache;
    private stats;
    private readonly MIN_SIZE_FOR_OPTIMIZATION;
    private readonly DEFAULT_SKIP_CACHE_CHARS;
    private readonly DEFAULT_SKIP_CACHE_LINES;
    private readonly IMPLICIT_STREAM_CHUNK_MIN_CHARS;
    private readonly MIN_LIST_LINES_FOR_MERGE;
    private readonly MIN_LIST_CHARS_FOR_MERGE;
    private readonly MIN_TABLE_LINES_FOR_MERGE;
    private readonly MIN_TABLE_CHARS_FOR_MERGE;
    private readonly MIN_UNBOUNDED_APPEND_TOTAL_CHARS;
    private readonly MIN_UNBOUNDED_APPEND_CHARS;
    private readonly MIN_UNBOUNDED_APPEND_LINES;
    constructor(core: ParserCore);
    reset(): void;
    resetStats(): void;
    parse(src: string, env: Record<string, unknown> | undefined, md: MarkdownIt): Token[];
    private recordChunkedParseResult;
    private parseFullDocument;
    private shouldUseUnboundedAppend;
    private getAppendedSegment;
    private tryTailSegmentReparse;
    private getTailLines;
    private endsInsideOpenFence;
    peek(): Token[];
    getStats(): StreamStats;
    private appendTokens;
    private updateCacheLineCount;
    private detectGlobalStateForAppend;
    private ensureLastSegment;
    private getLastSegment;
    private getLineStartOffset;
    private getLineStartOffsetFrom;
    private mayContainReferenceDefinition;
    private canDirectlyParseAppend;
    private tryContainerTailAppendMerge;
    private tryListTailAppendMerge;
    private tryTableTailAppendMerge;
    private getTableHeaderContext;
    private getTableBodySection;
    private isSingleTopLevelContainer;
    private getListParagraphMode;
    private setListParagraphVisibility;
    private shouldPreferTailReparseForAppend;
    private endsWithBlankLine;
    private getDocLineCount;
    private shiftTokenLines;
}
export default StreamParser;
